export const featuredProjects = [
  {
    id: 1,
    title: "KIN Tickets",
    slug: "kin-tickets",
    category: "Event Ticketing Platform",
    description:
      "A modern event management and ticketing platform with secure ticket purchasing, QR code validation, staff portal, and real-time admissions management.",
    image: "/images/kinProjects.png",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "MongoDB",
      "Stripe",
    ],
    features: [
      "Online Ticket Booking",
      "QR Code Scanner",
      "Staff Dashboard",
      "Event Management",
      "Secure Payments",
      "Responsive Design",
    ],
    liveUrl: "https://kintickets.dk/",
    githubUrl: "",
    featured: true,
    status: "Completed",
  },
  {
    id: 2,
    title: "VNET",
    slug: "vnet",
    category: "AI Learning & Personal Growth Platform",
    description:
      "A premium AI-powered platform focused on fitness, mental wellness, education, and career development through personalized learning paths.",
    image: "/images/vnetProjects.png",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "MongoDB",
      "AI Integration",
    ],
    features: [
      "AI Assessments",
      "Subscription Plans",
      "Expert Programs",
      "User Dashboard",
      "Progress Tracking",
      "Responsive UI",
    ],
    liveUrl: "https://venetconsultation.netlify.app/",
    githubUrl: "",
    featured: true,
    status: "In Development",
  },
  {
    id: 3,
    title: "RingMig",
    slug: "ringmig",
    category: "Listener & Booking Platform",
    description:
      "A real-time communication platform where users can book professional listeners, schedule sessions, and communicate through secure video and audio calls.",
    image: "/images/ringmigProjects.png",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "MongoDB",
      "Agora",
      "Stripe",
    ],
    features: [
      "Session Booking",
      "Video & Audio Calling",
      "Role-Based Dashboard",
      "Online Payments",
      "Calendar Scheduling",
      "Real-Time Notifications",
    ],
    liveUrl: "https://www.ring-mig.com/",
    githubUrl: "",
    featured: true,
    status: "Completed",
  },
];
