import Contact from "@/components/Contact";
import Navbar from "@/components/Navbar";
import { authOptions } from "@/lib/authOptions";
import { TUser } from "@/types/types";
import { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Oswald } from "next/font/google"; // Importing Oswald font

// Apply Oswald font globally
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CommonLayout = async ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  const session: TUser = await getServerSession(authOptions);
  console.log(session);
  return (
    <div
      className={`${oswald.variable} antialiased bg-black`}
      suppressHydrationWarning
    >
      <Navbar session={session} />
      {children}
      <Contact />
    </div>
  );
};

export default CommonLayout;
