import Navbar from "@/components/Navbar";
import { Metadata } from "next";
import { Oswald } from "next/font/google"; // Importing Oswald font

// Apply Oswald font globally
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CommonLayout = ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  return (
    <div className={`${oswald.variable} antialiased`}>
      <Navbar />
      {children}
    </div>
  );
};

export default CommonLayout;
